FROM node:10

RUN mkdir -p /usr/src/app/frontend
WORKDIR /usr/src/app/frontend

COPY package*.json ./

RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

EXPOSE 4200

CMD ["npm", "start"]